name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuda_tag: [ "12.4.1-runtime-ubuntu22.04", "12.8.0-runtime-ubuntu22.04" ]
        include:
          - cuda_tag: "12.4.1-runtime-ubuntu22.04"
            suffix: "cuda12.4"
          - cuda_tag: "12.8.0-runtime-ubuntu22.04"
            suffix: "cuda12.8"
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/bvgal/comfyui-runpod-template
          tags: |
            type=raw,value=${{ matrix.suffix }}
            ${{ matrix.suffix == 'cuda12.4' && 'type=raw,value=latest' || '' }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: CUDA_TAG=${{ matrix.cuda_tag }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
